# environment.yml
name: pyaqsapi
channels:
  - conda-forge
environment:
  - setuppyaqsapi
dependencies:
  - python>=3.9
  - conda-build
  - tox-conda
  - pandas
  - pep517
  - requests
  - setuptools
  - sphinx
  - sphinxcontrib-apidoc
  - sphinxcontrib-bibtex
  - toml
  - sphinx_rtd_theme
  - numpydoc
  - certifi
  - cryptography
  - pytest
  - python-build
  - pytest-rerunfailures
  - pytest-black
