# environment.yml
name: pyaqsapi
channels:
  - conda-forge
environment:
  - setuppyaqsapi
dependencies:
  - black
  - build
  - certifi
  - conda-build
  - cryptography
  - keyring
  - mypy
  - numpydoc
  - pip
  - pylint
  - pytest
  - pytest-black
  - pytest-cov
  - pytest-rerunfailures
  - pytest-sugar
  - python>=3.10
  - python-build
  - ratelimit
  - requests
  - ruff
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-bibtex
  - tox
  - wheel
