# environment.yml
name: pyaqsapi
channels:
  - conda-forge
environment:
  - setuppyaqsapi
dependencies:
  - python>=3.10
  #- conda-build
  # - tox-conda # currently, tox-conda is incompatible with tox>=4.0
  - pip
  - wheel
  - setuptools
  - pandas
  - ratelimit
  - requests
  - setuptools
  - sphinx
  - sphinxcontrib-apidoc
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - numpydoc
  - certifi
  - cryptography
  - python-build
  - pytest
  - pytest-sugar
  - pytest-rerunfailures
  - pytest-black
  - pytest-cov
  - pytest-sugar
  - tox
